### PR TITLE
Use `= default` for virtual constructors.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
FYI @nunoplopes

**Comment by NikolajBjorner** [comment]
@nunoplopes - is this OK to merge?

**Comment by nunoplopes** [comment]
Sorry, was on vacations. It's good, yes, thank you!

**Comment by NikolajBjorner** [comment]
Correct, I noticed it turned into August, the sacred month of scouts digging a trench for their poop.

**Pull request merged**
