### PR TITLE
support for MING64 

### PR DESCRIPTION
**Pull request by eactor**
use of platform.uname instead of os.uname
get.environ to destinguish between windows and mingw-msys derivate

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
We will have to revert parts of this due to build failure:

2017-12-19T16:00:09.0757238Z BUILD DATE: 2017-12-19
2017-12-19T16:00:09.3086797Z Switched to a new branch 'master'
2017-12-19T16:00:09.3086797Z Branch master set up to track remote branch master from origin.
2017-12-19T16:00:11.0742645Z From https://github.com/z3prover/z3
2017-12-19T16:00:11.0742645Z  * branch              master     -> FETCH_HEAD
2017-12-19T16:00:11.2148806Z Already up-to-date.
2017-12-19T16:00:12.0145324Z Traceback (most recent call last):
2017-12-19T16:00:12.0145324Z   File "scripts\mk_make.py", line 9, in <module>
2017-12-19T16:00:12.0145324Z     from mk_util import *
2017-12-19T16:00:12.0145324Z   File "C:\z3-build\vsagent\_work\1\s\scripts\mk_util.py", line 597, in <module>
2017-12-19T16:00:12.0145324Z     if(os.environ['MSYSTEM'].startswith('MSYS') or os.environ['MSYSTEM'].startswith('MINGW')):
2017-12-19T16:00:12.0145324Z   File "C:\Python36_x86\lib\os.py", line 669, in __getitem__
2017-12-19T16:00:12.0145324Z     raise KeyError(key) from None
2017-12-19T16:00:12.0145324Z KeyError: 'MSYSTEM'
2017-12-19T16:00:12.0274931Z Content of build\master\debug:
2017-12-19T16:00:12.0274931Z Traceback (most recent call last):
2017-12-19T16:00:12.0274931Z   File "scripts/win32test.py", line 27, in <module>
2017-12-19T16:00:12.0274931Z     win32test()
2017-12-19T16:00:12.0274931Z   File "scripts/win32test.py", line 13, in win32test
2017-12-19T16:00:12.0274931Z     util.buildz3(branch=b, everything=True, clean=True, debug=d, dotnet=True, java=True, static=False, jobs=1, clang=False, VS64=False)
2017-12-19T16:00:12.0274931Z   File "C:\z3-build\vsagent\_work\1\s\z3test\scripts\util.py", line 173, in buildz3
2017-12-19T16:00:12.0274931Z     mk_make(branch, debug, dotnet, java, clang, static, VS64, extraflags)
2017-12-19T16:00:12.0274931Z   File "C:\z3-build\vsagent\_work\1\s\z3test\scripts\util.py", line 137, in mk_make
2017-12-19T16:00:12.0274931Z     raise Exception("Failed to execute mk_make\n%s" % cmd)
2017-12-19T16:00:12.0274931Z Exception: Failed to execute mk_make

**Comment by NikolajBjorner** [comment]
I had to revert this one. There were too many quality issues with the pull request. It needs testing on other platforms before it is ready and the tabs have to go away to make the changes align with other parts of the script. Also, doesn't the cmake build system obsolete precisely these kinds of Brownian activities on platform compatibility?

**Comment by eactor** [comment]
I’m sorry about that that code fails. I only tested on RHEL 7 besides Windows. The CMAKE flow doesn’t compile at all for MSYS right now.
So I adjusted the Phyton stuff on our side to make it work for us.
I’m willing to further contribute if you are not saying I should put my effort towards cmake.

Von: Nikolaj Bjorner [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Dezember 2017 17:20
An: Z3Prover/z3 <z3@noreply.github.com>
Cc: Ehrlich, Paul <paul.ehrlich@coseda-tech.com>; Author <author@noreply.github.com>
Betreff: Re: [Z3Prover/z3] support for MING64 (#1412)


I had to revert this one. There were too many quality issues with the pull request. It needs testing on other platforms before it is ready and the tabs have to go away to make the changes align with other parts of the script. Also, doesn't the cmake build system obsolete precisely these kinds of Brownian activities on platform compatibility?

**Comment by NikolajBjorner** [comment]
I am in favor of retiring the legacy build system for reasons related to the kind of issues we are running into. cmake is set up to be much more systematic for cross compiler and platform builds, than the home made scripts. That said, there are some things that don't work yet with cmake (ocaml) and it will be necessary to go with both still. 

I should be able to reproduce (and fix) build issues with your pull request locally. I am a bit short on cycles for some time now so it would be very nice to figure out a way to fix things inside the pull request or a new version of it and then everybody can benefit form your fixes for MSYS sooner.

**Pull request merged**
