### PR TITLE
Handle third argument of str.indexof in Z3str3 

### PR DESCRIPTION
**Pull request by mtrberzi**
Addresses issues with `str.indexof` raised in #1379 and #1367.

Hopefully the Mac build does not throw this time -- if it does I will potentially have more time to work on the fix.

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
Testing regressions/smt2/string13.smt2

EXPECTED

unsat

unsat


======================

PRODUCED

unsat

ast_manager LEAKED: 16

Leaked: #1119 := (str.++ $$_str15!tmp54[$$_str15!tmp54] ts1!tmp18[ts1!tmp18])

decl c1 :: String[bv[8]]

#106 := (str.++ c1 x2!tmp8[x2!tmp8])

(= #106 #1119)

id: 26478

unsat


======================

Failed

**Comment by NikolajBjorner** [comment]
The debug build reports leaked expressions

**Comment by mtrberzi** [comment]
Last patch fixed the leaked expression, just need to address the timeout.

**Comment by mtrberzi** [comment]
Looks like the latest patch resolved the issue, should be ready for review.

**Pull request merged**
