### PR TITLE
Fixed parsing of | and \

### PR DESCRIPTION
**Pull request by CEisenhofer**
The \ does not only escape the | but also counts itself as a character of the name. Also, \\ does not escape \

e.g.,
In SMT-LIB input |\|| becomes |\\\|| 
|\\| becomes |\\\\|
|\\|| becomes |\\\\\|
...

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
- separate scanner changes from user-propagator
- esp. for a change to old code paths add unit test that establishes bug vs fix.

**Comment by CEisenhofer** [comment]
This is not related to user-propagation 🤔

**Comment by CEisenhofer** [comment]
Where should parsing unit-tests go to?
test/smt2print_parse.cpp ?

**Comment by NikolajBjorner** [comment]
either in a new or old file in the test directory yes.

**Pull request closed without merging**
