### PR TITLE
Add support for MSYS2

### PR DESCRIPTION
**Pull request by Uni-**
With this patch, Z3 is compiled via MSYS shell and toolchain of MSYS2. (MINGW32 shell and MINGW64 shell is not yet cared.)

### CODE REVIEW

**Comment by wintersteiger** [comment]
Our scripts already supported mingw, see `is_cygwin_mingw()` and `IS_CYGWIN_MINGW`. Do we really want `-D_CYGWIN` when compiling via mingw?

**Comment by Uni-** [comment]
It's MSYS2, MinTTY subsystem running MinGW-w64 toolchain, based on recent Cygwin fork. It's different from traditional cmd.exe running MinGW toolchain.

When I run `./configure` in the MSYS shell, I got this error:

````
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/Eon/Development/z3/scripts/mk_util.py", line 2575, in mk_makefile
    mk_config()
  File "/home/Eon/Development/z3/scripts/mk_util.py", line 2474, in mk_config
    raise MKException('Unsupported platform: %s' % sysname)
mk_exception.MKException: 'Unsupported platform: MSYS_NT-10.0'
````

What I got with `./configure` in MINGW64 shell is:

````
Writing build/Makefile
Copied Z3Py example 'all_interval_series.py' to 'build/python'
Copied Z3Py example 'example.py' to 'build/python'
Copied Z3Py example 'socrates.py' to 'build/python'
Copied Z3Py example 'visitor.py' to 'build/python'
Makefile was successfully generated.
  compilation mode: Release
  platform: x86
To build Z3, open a [Visual Studio Command Prompt], then
type 'cd C:/Users/Eon/Development/z3/build && nmake'

Remark: to open a Visual Studio Command Prompt, go to: "Start > All Programs > Visual Studio > Visual Studio Tool
````

You're right, we may not want `-D_CYGWIN` in MSYS shell really.

**Comment by Uni-** [comment]
@wintersteiger My conclusion is, in short, it's good to set `-D_CYGWIN` in build script for current source code when compiling in MSYS2. If you think the macro name is inappropriate for MSYS2, every appearance of the name _CYGWIN should be modified in source code.

**Comment by wintersteiger** [comment]
This is not about the appropriateness of the macro name. On the MSYS2 platform we are not supposed to behave like we do on the Cygwin platform (adding -D_CYGWIN changes the behavior of Z3). Also, we already had support for mingw/msys, we just didn't recognize that particular version string yet. 

I'm trying to add another commit to this PR/branch, but GitHub is acting up.

**Pull request closed without merging**
