### PR TITLE
[TravisCI] Enable macOS build

### PR DESCRIPTION
**Pull request by delcypher**
Only one configuration is enabled due to macOS builds taking a long time to start. This is based on previous experience. We can easily add more configurations later if we really need them.

### CODE REVIEW

**Comment by delcypher** [comment]
This is currently failing for reasons unrelated to this PR as far as I know. See #1206

**Comment by delcypher** [comment]
@wintersteiger The OSX builds run on TravisCI's own build machines just like the Linux builds. I am not aware of any additional conditions when running on OSX. There's certainly no mention of "apple"/"macos"/"osx" in [their terms of service](https://billing.travis-ci.com/pages/terms). I am not a lawyer though.

If you want to know about OSX environment itself [see here](https://docs.travis-ci.com/user/reference/osx/).

We already have working builds of this configuration. Here's an example
https://travis-ci.org/Z3Prover/z3/jobs/264172108

**Comment by wintersteiger** [comment]
This isn't so much about Travis' T&C, but about Apple's. When last I checked it was illegal to run OSX on a VM, i.e. you had to run on Apple hardware, and this is also the reason for me having a Mac Mini on my office desk (and for Azure and AWS not offering OSX VMs). The Travis OSX environment overview starts with "Travis CI runs builds in virtual machines...", and I wouldn't want to get into trouble over that. Can you please disable these builds until we have figured out the legal situation?

**Comment by delcypher** [comment]
I'm not sure if it's still relevant but at least in the past TravisCI used a third party service (called [MacStadium](https://www.macstadium.com/) for their Mac machines. MacStadium appear to provide bare-metal macs.

There's an article on the site specifically about TravisCi

https://www.macstadium.com/customers/travis-ci/

If TravisCI is not using mac machines for their builds then that would be illegal for all projects that use them (not just Z3) which I highly doubt is the case.

However I will create a PR to disable the macOS configuration for now. I suggest you reach out to TravisCI team (they've been pretty responsive to my e-mails in the past) to assuage your legal concerns.

It would be nice to solve this reasonably quickly though because having macOS tested as well as Linux is useful.

**Comment by delcypher** [comment]
@wintersteiger PR created ( #1208 )

**Comment by NikolajBjorner** [comment]
Seems that the more likely situation is that Travis is a business that ensures its infrastructure is properly licensed, e.g., uses Mac based services where appropriate.

**Comment by wintersteiger** [comment]
@NikolajBjorner Sure, one would expect so many things... They claim to have found an "amazing sponsor" (see https://github.com/travis-ci/travis-ci/issues/216), but I haven't found any clear statement on this issue yet. I'm fine with having Travis builds on OSX, but for now we should use our own hardware (if Travis allows us to do that).

**Comment by delcypher** [comment]
@wintersteiger @NikolajBjorner Moving discussion to new issue (#1211) as this PR was already merged.

**Pull request merged**
