### PR TITLE
Minor python-related style fixes

### PR DESCRIPTION
**Pull request by daniel-j-h**
Initially I wanted to improve the build system; but then I realized it's a > 5k loc subproject in itself..

So here it goes; with a few minor issues, such as indentation with 3 spaces mixed in and a lot of un-pythonic style, such as semi-colon at end of line.

See #27

### CODE REVIEW

**Comment by wintersteiger** [comment]
In Python, is there any difference in semantics between `if q != None ...` and ` if q is not None ...`? If not, then I'd prefer to keep `!=`. You're definitely right about the semicolons though, those should indeed be removed.

**Comment by daniel-j-h** [comment]
`if q is not None` is the idiomatic way of doing it, see also: http://stackoverflow.com/a/2209781

It does not make a difference here from a quick glance (since the changes are a bit dated by now).

**Comment by cheshire** [comment]
`!=` will be probably slower, as it will check for overloaded equality method.

**Comment by wintersteiger** [comment]
That sounds good, then we'll switch those to the preferred `is not`. Since this touches a lot of lines of code, I might have to run some tests before I can get that merged. 

Also, if it's not too much trouble, could I get you to sign a [CLA](https://github.com/Z3Prover/z3/wiki/Contribution-Guidelines)?

**Comment by daniel-j-h** [comment]
@wintersteiger signed.

**Comment by wintersteiger** [comment]
Sorry for the premature closer; this is being merged now.

**Comment by wintersteiger** [comment]
Merged into master as of df1f60062498e43c8924575641f5f326d3c17cfa

**Pull request closed without merging**
