### PR TITLE
Cleanup z3util python module

### PR DESCRIPTION
**Pull request by tpaviot**
pylint and codespell issues fixes: remove trailing whitespaces, remove extraneous newlines, unnecessary else/elif after return, dangerous [] as default argument value (https://satran.in/b/python--dangerous-default-value-as-argument), typo.

### CODE REVIEW

**Comment by tpaviot** [comment]
Sorry, I did not realize I have to sign the MS CLA. I don't agree with some of the terms.

**Comment by NikolajBjorner** [comment]
Sorry. It for sure would appear to be overkill for a pull request around python utilities.
An important reason why we have this in place is to give commercial companies assurance 
that if they ship with Z3 there isn't something out of the blue they get held liable about.
I don't think the intent is to irritate contributors.

**Comment by tpaviot** [comment]
No problem, I understand, I should have carefully read the contributor guidelines. z3 is a great project, I wish I could contribute some code to the python api, it needs an overall cleanup to be consistent with python3 coding rules. But it works quite well as is, these are only cosmetic changes.

**Comment by NikolajBjorner** [comment]
You are invited to point out what should be changed for Python 3 and I can try to follow the advise.

**Pull request closed without merging**
