### PR TITLE
Add flag to mk_make.py to optionally enable Control Flow Guard

### PR DESCRIPTION
**Pull request by danpere**
Adds a flag (disabled by default) `--guardcf` to `mk_make.py` to enable [Control Flow Guard checks](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-guard-checks), which is a security feature that checks that indirect calls go to known good addresses. `libz3.dll` compiled with this flag satisfies [`binskim`](https://github.com/Microsoft/binskim)'s security checks. This PR leaves it disabled by default as it may have a performance impact.

### CODE REVIEW

**Comment by delcypher** [comment]
@danpere I don't suppose you'd be interested in adding this to the CMake build system too?

**Comment by wintersteiger** [comment]
That's great, thanks a lot! 

As @delcypher says, it would be great if you could add that to the cmake system as well.

**Comment by danpere** [comment]
I had seen the comments about wanting to get rid of the Python build system in favor of CMake, but I hadn't found the MSVC path in CMake when making the PR. I think I see how to do it now, but won't have time to do the PR today, so I'll probably do it Monday. Also, doing research for this, I notice that `llvm` has a similar feature called [Control Flow Integrity](https://clang.llvm.org/docs/ControlFlowIntegrity.html); I'll figure out the right flags so when compiling `z3` with `clang`, that feature will be used.

**Comment by NikolajBjorner** [comment]
super, thanks!

**Pull request merged**
