### PR TITLE
Fixed utf-8 version string handling for python2. Resolved #787

### LINKED ISSUE #787: Python 2 installation issue: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 35: ordinal not in range(128)
```
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 2567, in mk_makefile
    mk_config()
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 2434, in mk_config
    if is_CXX_clangpp():
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 885, in is_CXX_clangpp
    return is_clang_in_gpp_form(CXX)
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 881, in is_clang_in_gpp_form
    return str(version_string).find('clang') != -1
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 35: ordinal not in range(128)
```

when running `python scripts/mk_make.py` command. I've found that the CXX env refers to `g++` with native language characters (e.g. Chinese one is `g++ (GCC) 6.2.1 20160830
Copyright © 2016 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。`) thus it cannot resolve non-ASCII characters by default. Manually insert `sys.setdefaultencoding('utf-8')` works fine.

### PR DESCRIPTION
**Pull request by legendtang**

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
looks fine.

**Comment by wintersteiger** [comment]
Not sure this will work correctly with Python 3 and GCC (unicode characters in --version output).

**Comment by legendtang** [comment]
@wintersteiger Of course. I tested both on Python 2 and Python 3.

**Comment by wintersteiger** [comment]
Merging without further tests. The nightly builds will fail if anything's wrong with this.

**Pull request merged**
