### PR TITLE
Standardize on __uint64 instead of unsigned __int64

### PR DESCRIPTION
**Pull request by ddcc**

### CODE REVIEW

**Comment by wintersteiger** [comment]
That looks good, thanks for the fix!

**Comment by delcypher** [comment]
@wintersteiger @ddcc 
Is there any reason not to use `uint64_t` (from `stdint.h`) instead of `__uint64`?

**Comment by wintersteiger** [comment]
@declyper: Historical platform compatibility. If I remember correctly, Visual Studio didn't support C99 until around VS 2010 or so? For earlier ones there was no stdint.h at all.

**Comment by ddcc** [comment]
One problem that I've run into is that `__uint64` and `uint64_t` are incompatible on some platforms; the former is declared as a `unsigned long long`, whereas on most x86_64 Linux platforms, the latter is declared as a `unsigned long`. Even though they're both 8 bytes, the two aren't implicitly convertible without an explicit cast.

**Comment by delcypher** [comment]
@wintersteiger I wasn't aware that MSVC ever supported C99. I thought it was stuck at C89. I think C++ expects the header to exist though (as `#include <cstdint>`).

@ddcc That's interesting and also very unfortunate.

**Pull request merged**
