### PR TITLE
Z3str3 Debug

### PR DESCRIPTION
**Pull request by JohnLyu2**
[DebuggingZ3str3.docx](https://github.com/Z3Prover/z3/files/8557176/DebuggingZ3str3.docx)

Fixed the bugs in Z3str3 mentioned in the attached document. Also, comments are added in the code base referencing to the bugs in the document.

Thanks,
John

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
can you comment on bugs that can be closed?

**Comment by JohnLyu2** [comment]
> can you comment on bugs that can be closed?

Yes, I will take a look at all the open issues with the label "z3str3" and let you know the results.

**Comment by JohnLyu2** [comment]
I think issues #2598 , #4352 , #4364 , #4453 , #5278 can be closed now. I will keep digging into the remaining open str3 issues.

**Comment by NikolajBjorner** [comment]
closed

**Pull request merged**
