### PR TITLE
Use pass-by-value of expr_ref so that tests compile in g++

### PR DESCRIPTION
**Pull request by ahorn**

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
What is error? I tend to avoid cbv for structs. Alternative is to pass expr*

**Comment by ahorn** [comment]
A  test attempts to pass 0 to expr_ref&. Here's the important bits of the error message:

../src/test/pdr.cpp:52:22: note: in expansion of macro ‘alloc’
             add_tree(alloc(model_node, parent, mk_state(states, rand), pt, level-1), false);
                      ^
In file included from ../src/test/pdr.cpp:1:0:
../src/muz/pdr/pdr_context.h:201:9: note: pdr::model_node::model_node(pdr::model_node*, expr_ref&, pdr::pred_transformer&, unsigned int)
         model_node(model_node* parent, expr_ref& state, pred_transformer& pt, unsigned level):
         ^
../src/muz/pdr/pdr_context.h:201:9: note:   no known conversion for argument 2 from ‘expr_ref {aka obj_ref<expr, ast_manager>}’ to ‘expr_ref& {aka obj_ref<expr, ast_manager>&}’
../src/muz/pdr/pdr_context.h:187:11: note: pdr::model_node::model_node(const pdr::model_node&)
     class model_node {
           ^
../src/muz/pdr/pdr_context.h:187:11: note:   candidate expects 1 argument, 4 provided
In file included from ../src/util/vector.h:30:0,
                 from ../src/ast/ast.h:22,
                 from ../src/ast/rewriter/bool_rewriter.h:22,
                 from ../src/muz/pdr/pdr_manager.h:26,
                 from ../src/muz/pdr/pdr_context.h:28,
                 from ../src/test/pdr.cpp:1:
../src/util/memory_manager.h:87:69: error: no matching function for call to ‘pdr::model_node::model_node(pdr::model_node*&, expr_ref, pdr::pred_transformer&, unsigned int)’
 #define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
                                                                     ^
../src/test/pdr.cpp:53:22: note: in expansion of macro ‘alloc’
             add_tree(alloc(model_node, parent, mk_state(states, rand), pt, level-1), false);
                      ^
../src/util/memory_manager.h:87:69: note: candidates are:
 #define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
                                                                     ^
../src/test/pdr.cpp:53:22: note: in expansion of macro ‘alloc’
             add_tree(alloc(model_node, parent, mk_state(states, rand), pt, level-1), false);
                      ^
In file included from ../src/test/pdr.cpp:1:0:
../src/muz/pdr/pdr_context.h:201:9: note: pdr::model_node::model_node(pdr::model_node*, expr_ref&, pdr::pred_transformer&, unsigned int)
         model_node(model_node* parent, expr_ref& state, pred_transformer& pt, unsigned level):
         ^
../src/muz/pdr/pdr_context.h:201:9: note:   no known conversion for argument 2 from ‘expr_ref {aka obj_ref<expr, ast_manager>}’ to ‘expr_ref& {aka obj_ref<expr, ast_manager>&}’
../src/muz/pdr/pdr_context.h:187:11: note: pdr::model_node::model_node(const pdr::model_node&)
     class model_node {
           ^
../src/muz/pdr/pdr_context.h:187:11: note:   candidate expects 1 argument, 4 provided
In file included from ../src/util/vector.h:30:0,
                 from ../src/ast/ast.h:22,
                 from ../src/ast/rewriter/bool_rewriter.h:22,
                 from ../src/muz/pdr/pdr_manager.h:26,
                 from ../src/muz/pdr/pdr_context.h:28,
                 from ../src/test/pdr.cpp:1:
../src/test/pdr.cpp: In member function ‘void test_model_search::init()’:
../src/util/memory_manager.h:87:69: error: no matching function for call to ‘pdr::model_node::model_node(int, expr_ref, pdr::pred_transformer&, unsigned int&)’
 #define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
                                                                     ^
../src/test/pdr.cpp:94:32: note: in expansion of macro ‘alloc’
             model_node* root = alloc(model_node, 0, mk_state(states, rand), pt, level);
                                ^
../src/util/memory_manager.h:87:69: note: candidates are:
 #define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
                                                                     ^
../src/test/pdr.cpp:94:32: note: in expansion of macro ‘alloc’
             model_node* root = alloc(model_node, 0, mk_state(states, rand), pt, level);
                                ^
In file included from ../src/test/pdr.cpp:1:0:
../src/muz/pdr/pdr_context.h:201:9: note: pdr::model_node::model_node(pdr::model_node*, expr_ref&, pdr::pred_transformer&, unsigned int)
         model_node(model_node* parent, expr_ref& state, pred_transformer& pt, unsigned level):
         ^
../src/muz/pdr/pdr_context.h:201:9: note:   no known conversion for argument 2 from ‘expr_ref {aka obj_ref<expr, ast_manager>}’ to ‘expr_ref& {aka obj_ref<expr, ast_manager>&}’
../src/muz/pdr/pdr_context.h:187:11: note: pdr::model_node::model_node(const pdr::model_node&)
     class model_node {
           ^
../src/muz/pdr/pdr_context.h:187:11: note:   candidate expects 1 argument, 4 provided
Makefile:3703: recipe for target 'test/pdr.o' failed

**Comment by ahorn** [comment]
Is commit 23143f3 what you have in mind?

**Comment by nunoplopes** [comment]
please submit a new patch for the unstable branch. Thanks!

**Comment by wintersteiger** [comment]
The unstable branch is not used anymore; all ne PRs should be based on master.

**Pull request closed without merging**
