### PR TITLE
If ocamlfind is installed, add destdir/stublibs to rpath

### PR DESCRIPTION
**Pull request by zkincaid**
Fixes the LD_LIBRARY_PATH issue mentioned [here](https://github.com/Z3Prover/z3/issues/34#issuecomment-91525424).

This is the same patch proposed [here](https://github.com/Z3Prover/z3/pull/128).

### CODE REVIEW

**Comment by Drup** [comment]
Can we get this merged ?

**Comment by wintersteiger** [comment]
Yes we are very close to getting this merged. Could you review the discussion for #34 again? Perhaps we should always rely on a system installed shared library for Z3?

The proposed patch does not work for me. I'm using Windows 10, OCaml 4.02.1 (win32 native, cl, no cygwin involved). `ocamlfind printconf destdir` reports `C:\ocamlw32\lib\site-lib` and the latter does not contain a directory called `stublibs`.

**Comment by zkincaid** [comment]
Apparently, ocamlfind installs DLLs into `stublibs` if it exists in `ocamlfind printconf destdir`, and otherwise installs them in the package directory.  I believe that OPAM creates the stublibs directory by default.  This should be fixed now, but I don't have a windows machine to test it on.

**Comment by wintersteiger** [comment]
Tested, works on Windows too, so I'm merging this into master now.

**Comment by wintersteiger** [comment]
Merged into master as of 3aedcf0a7e38d842dc0d3e43ec7343a67206a9b0

**Pull request closed without merging**
