### PR TITLE
Add pkg-config file

### PR DESCRIPTION
**Pull request by XVilka**
Added pkg-config file to simplify life of the dependent projects.

Closes https://github.com/Z3Prover/z3/issues/4367

cc @anthraxx

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
there is some typo in the pull request

**Comment by XVilka** [comment]
Fixed and tested. Sorry for the trouble.

**Comment by NikolajBjorner** [comment]
Travis seems unhappy ATM

CMake Error: File /home/user/z3_src/z3.pc.cmake.in does not exist.

**Comment by NikolajBjorner** [comment]
The Azure pipelines are good (the two failures are external to this pull request)

**Comment by XVilka** [comment]
I am not sure why Travis CI is unhappy - I am unfamiliar with your Travis setup. Clearly file is here, maybe some checkout problem?

**Comment by NikolajBjorner** [comment]
I am not in a good position to help on the Travis setup. 
I have no particular expertise and would have to read the scripts to get familiar with what the source of the issue would be.

**Comment by XVilka** [comment]
Ok, now that Travis problem is fixed.

**Pull request merged**
