### PR TITLE
mk_util.py, fix tabs/spaces mix, remove trailing whitespace, remove unused modules

### PR DESCRIPTION
**Pull request by cao**
Subject says it all :)

### CODE REVIEW

**Comment by cao** [comment]
It does not matter much here probably, but I signed the CLA just in case. :)

**Comment by NikolajBjorner** [comment]
😁

**Comment by wintersteiger** [comment]
These all look good, thanks for the patches, they'll be merged soon!

**Comment by wintersteiger** [comment]
Merged into master as of 4f50c28c352ef1f6b3750f88cda8fc6acfc50859

**Pull request merged**
