### PR TITLE
Update injectivity tactic

### PR DESCRIPTION
**Pull request by nbraud**
- [x] Add extra rewriter for `(g (f x)) -> (x)`.
- [x] Add parameters controlling which rewriters are called.
- [x] Support UNSAT core generation.

This is a follow-up on #1225.

### CODE REVIEW

**Comment by nbraud** [comment]
@wintersteiger Interestingly, this works fine using `check-sat-using`, but adding it to the default tactic segfaults  :/
Here is the patch I used for the « hacked » build: https://paste.debian.net/hidden/747b0349/
(It turns out patches are not valid attachments on Github...)

**Comment by nbraud** [comment]
This seems to be caused by the `params_ref` object going `NULL` while the `injectivity_params` object is still live.  It probably involves Z3 object wizardry beyond my ken.  :(

**Comment by nbraud** [comment]
Note to self: Clang has an helpful comment about passing a temporary to a member's constructor.

**Comment by wintersteiger** [comment]
@nbraud did you figure out what's going wrong there?

**Comment by nbraud** [comment]
@wintersteiger I was ill the past 2 weeks and didn't have a change to poke at it, but it's likely the lifetime issue you pointed out.

**Comment by NikolajBjorner** [comment]
is this ready or should it be retired?

**Comment by NikolajBjorner** [comment]
no activity for 18 months

**Pull request closed without merging**
