### PR TITLE
Optimize module for ML bindings, second edition.

### PR DESCRIPTION
**Pull request by Drup**
As noted last time, there are no functions in the C API to
- Get the reason for UNKNOWN
- Get the unsat core

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
we have to clear the process for merging pull requests before we can do it, sorry.
I added ML bindings in the opt branch two weeks ago and took them now to unstable.
Added get_reason_unknown. Not adding core support yet. It can so far be emulated by using a solver when retrieving unsat, so it depends if it is an important user scenario to add this functionality.

**Comment by Drup** [comment]
Ok, thanks. At least it's in now.

**Comment by wintersteiger** [comment]
Am I correct in assuming that this PR is obsolete after @NikolajBjorner added an Optimize module to the ML API?

**Comment by NikolajBjorner** [comment]
Obsolete

**Pull request closed without merging**
