### PR TITLE
Refactor OCaml generated file generation in preparation for CMake support

### PR DESCRIPTION
**Pull request by delcypher**
This is a set of refactorings that are necessary to implement CMake support for building the Z3 OCaml bindings.

This is very similar to previous refactorings I have done to support the Python, Java and .NET bindings in CMake.

Note this doesn't implement the CMake support. I will do that in a separate PR once this is approved.

### CODE REVIEW

**Comment by wintersteiger** [comment]
Sorry, this will take some time to review. OCaml is unbelievably picky about file names, locations, and module names, etc.

**Comment by delcypher** [comment]
@wintersteiger No problem. It's also going to take me a long time to support the OCaml bindings in CMake as I'm not at all familiar with the language and how it is built. However I thought I'd made a start by doing the necessary refactoring.

By the way there was a large amount of commented out code. I've preserved it but I think it ought to be removed as it's doing nothing useful right now.

**Comment by wintersteiger** [comment]
Yes, those comments are previous/alternative implementations. The overall strategy for those bindings changed multiple times... pretty much with every minor version release of OCaml :) 

@martin-neuhaeusser: Could you take a look at this and perhaps coordinate with @delcypher so we can get this done with a minimum number of rabbit holes explored per person?

**Comment by martin-neuhaeusser** [comment]
I can try to help here - actually I promised to integrate the OCaml bindings into CMake some time ago, but had no time to actually do it.

**Comment by martin-neuhaeusser** [comment]
I successfully built Z3's OCaml bindings with @delcypher's refactoring and the python build system. So I think the patch preserves the old behavior; looking at the code, it is mostly moving code to separate the build and makefile generation stuff - which is good.

**Comment by delcypher** [comment]
@martin-neuhaeusser Thanks for testing.

**Comment by delcypher** [comment]
@wintersteiger Are there any platforms you'd like me to test to speed things along?

Related to this in #410 I mentioned having public continuous integration testing. Did that ever get set up? It be would be nice to have so that a simple refactoring does not require lots of manual testing.

**Comment by wintersteiger** [comment]
@delcypher Definitely Linuxes and OSX. OCaml on Windows is very tricky and basically every installation is different, so don't bother with that for now. 

Re integration testing: We have that and it's public, but it's doesn't run on community-accessible machines. I haven't found any solution that would allow us to do all of Windows, Linux, and OSX though. I have a few build machines set up, interfaced through the visualstudio.com, but it's not live yet.

**Comment by delcypher** [comment]
@wintersteiger Sorry for being slow. I'm going to be pretty busy these next few days but I'll give those platforms a try sometime next week.

**Comment by martin-neuhaeusser** [comment]
For Windows, I can try out building with OCaml bindings via Cygwin and the mingw-w64 cross-compiler.

**Comment by delcypher** [comment]
Just tested Ubuntu 14.04LTS. I tried building Z3 and the OCaml bindings and then running the OCaml example. I did not run into any problems.

**Comment by delcypher** [comment]
Just tested Ubuntu 16.04LTS. I tried building Z3 and the OCaml bindings and then running the OCaml example. I did not run into any problems. I used version `4.02.3-5ubuntu2` of the ocaml package.

**Comment by delcypher** [comment]
Just tested macOS Sierra. I did run into a small problem

```
$ make -j4
...
ocamlc  -ccopt "-D_MP_INTERNAL -D_AMD64_ -DNDEBUG -D_EXTERNAL_RELEASE -fvisibility=hidden -c -mfpmath=sse -msse -msse2 -D_NO_OMP_ -O3 -D _EXTERNAL_RELEASE -fomit-frame-pointer -Wno-unknown-pragmas -Wno-overloaded-virtual -Wno-unused-value -fPIC -I /usr/local/lib/ocaml -I ../src/api -I ../src/api/ml -o api/ml/z3native_stubs.o" -c ../src/api/ml/z3native_stubs.c
ocamlmklib -o api/ml/z3ml -I api/ml api/ml/z3native_stubs.o api/ml/z3enums.cmo api/ml/z3native.cmo api/ml/z3.cmo  -L. -lz3
ocamlmklib -o api/ml/z3ml -I api/ml api/ml/z3native_stubs.o  api/ml/z3enums.cmx api/ml/z3native.cmx api/ml/z3.cmx -L. -lz3
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: can't open file: api/ml/libz3ml.a (No such file or directory)
make: *** [api/ml/z3ml.cma] Error 2
make: *** Waiting for unfinished jobs....
users-iMac:build user$ ls api/ml
META			z3.cmi			z3.mli			z3enums.cmo		z3enums.o		z3native.cmi		z3native.mli
dllz3ml.so		z3.cmo			z3.o			z3enums.cmx		z3ml.a			z3native.cmo		z3native.o
libz3ml.a		z3.cmx			z3enums.cmi		z3enums.mli		z3ml.cmxa		z3native.cmx		z3native_stubs.o
users-iMac:build user$
```

I ran `make` again and the build succeed. The issue is likely due to the generated makefile not handling dependencies properly and running a parallel build which has notihng to do with this patch.

Anyway after doing that I built the `ml_example` and it ran successfully.

**Comment by delcypher** [comment]
@wintersteiger This is probably good to merge now.

The problem above relating to `libz3ml.a` is unrelated to this change AFAICT.

**Comment by delcypher** [comment]
To help you debug the above issue the `libz3ml.a` file seems to be generated by

both

```
ocamlmklib -o api/ml/z3ml -I api/ml api/ml/z3native_stubs.o api/ml/z3enums.cmo api/ml/z3native.cmo api/ml/z3.cmo  -L. -lz3
```

and by

```
ocamlmklib -o api/ml/z3ml -I api/ml api/ml/z3native_stubs$(OBJ_EXT)  api/ml/z3enums.cmx api/ml/z3native.cmx api/ml/z3.cmx -L. -lz3 
```

commands

**Comment by wintersteiger** [comment]
Well, this is not quite unrelated to this PR... we definitely don't want to carry this bug over to the cmake build! For the current build I just added an artificial dependency from the cmxa on he cma, that way one is always build before the other.

**Comment by delcypher** [comment]
@wintersteiger I meant unrelated in the sense that my change is not causing this behaviour. Would you like me to rebase this PR with your latest change and test?

**Comment by wintersteiger** [comment]
@delcypher: Yes please, that would be great, thanks! Did you also test the installation into ocamlfind? That was one of the trickier issues, but if the other files are still compiled with the same flags as before it should still work.

**Comment by delcypher** [comment]
@wintersteiger I'm rebuilding now. I tested that running `make install` succeeded but I didn't test whether the installation worked. I just built Z3 and checked that `make ml_example` worked and that the produced OCaml program worked as expected.

Installing `ocamlfind` was a pain. I had to do `brew install opam`, configure my shell the way opam wants and then `opam install ocamlfind`.

**Comment by delcypher** [comment]
@wintersteiger The rebuild succeeded and I didn't have a problems when building in parallel. The `ml_example` builds and works as expected.

**Comment by delcypher** [comment]
@wintersteiger 
I've tested using the OCaml bindings from the install. The OCaml bindings get installed outside of the install prefix so I wasn't expecting this to work.

```
$ sudo make install
WARNING: installing files/directories (/Users/user/.opam/system/lib) that are not in the install prefix (/usr/local).
Installed /Users/user/.opam/system/lib/Z3/z3ml.cmxs
Installed /Users/user/.opam/system/lib/Z3/z3ml.cmxa
Installed /Users/user/.opam/system/lib/Z3/z3ml.cma
Installed /Users/user/.opam/system/lib/Z3/z3ml.a
Installed /Users/user/.opam/system/lib/Z3/libz3ml.a
Installed /Users/user/.opam/system/lib/Z3/z3.cmx
Installed /Users/user/.opam/system/lib/Z3/z3.cmi
Installed /Users/user/.opam/system/lib/Z3/z3.mli
Installed /Users/user/.opam/system/lib/Z3/z3native.cmx
Installed /Users/user/.opam/system/lib/Z3/z3native.cmi
Installed /Users/user/.opam/system/lib/Z3/z3native.mli
Installed /Users/user/.opam/system/lib/Z3/z3enums.cmx
Installed /Users/user/.opam/system/lib/Z3/z3enums.cmi
Installed /Users/user/.opam/system/lib/Z3/z3enums.mli
Installed /Users/user/.opam/system/lib/Z3/META
Installed /Users/user/.opam/system/lib/stublibs/dllz3ml.so
Installed /Users/user/.opam/system/lib/stublibs/dllz3ml.so.owner
ocamlfind: [WARNING] You have installed DLLs but the directory /Users/user/.opam/system/lib/stublibs is not mentioned in ld.conf
Z3 was successfully installed.
```

However, I built the example manually (following `examples/ml/README`) against the installed Z3 package and it ran without problems (without needing to modify `/usr/local/lib/ocaml/ld.conf`).

I was slightly surprised by that but then again I don't have a good understanding of how OCaml compiler looks for packages or when it needs the files that were installed to `~/.pam/system/lib/Z3/*`.

DYLD (the runtime linker) reports when running the OCaml binary that the Z3 library is loaded from `/usr/local/lib/libz3.dylib` which looks correct from me.

Anyway for macOS the OCaml build and install looks fine with this PR.

**Comment by wintersteiger** [comment]
That's great, thanks for running those extra tests! I totally agree on ocamlfind (and a few related tools) being a bit of a pain, they have a lot of work to do on those. I think the OCaml community is moving toward opam for everything instead of system installed/managed packages, but we'll see for how long that lasts.

**Pull request merged**
