### PR TITLE
Fixed platform detection on MSYS (was #908)

### PR DESCRIPTION
**Pull request by wintersteiger**
This is a replacement for the broken PR #908.

### CODE REVIEW

**Comment by wintersteiger** [comment]
@Uni- Could you try this change to see whether Z3 compiles on your MSYS system with this?

**Comment by Uni-** [comment]
@wintersteiger, still same error as seen in #908. 

````
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/Eon/Development/z3/scripts/mk_util.py", line 2576, in mk_makefile
    mk_config()
  File "/home/Eon/Development/z3/scripts/mk_util.py", line 2475, in mk_config
    raise MKException('Unsupported platform: %s' % sysname)
mk_exception.MKException: 'Unsupported platform: MSYS_NT-10.0'
````

**Comment by wintersteiger** [comment]
What kind of Python do you use? Did you compile your own or is that in the MSYS package management repository somewhere?

**Comment by wintersteiger** [comment]
Bumping. Is this still a problem or has it been resolved?

**Comment by Uni-** [comment]
@wintersteiger, sorry for coming late. I use python2, python3 packages as-is delivered from MSYS Pacman. /usr/bin/python.exe is a copy of /usr/bin/python3.exe, as the packages default.

And still the same exception.

Thank you for your efforts, but I think you should see what's happening on the point build error occurs, [scripts/mk_util.py:2475 (at your commit 514f08f)](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L2475). The if-else around this line does not use is_cygwin_mingw(), but the raw uname. That's why at first I modified exactly that line in commit 387970f6 (initially suggested via #908).

Moreover, I think you commit 514f08f is going little weird. Please see [scripts/mk_util.py:614](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L614), [scripts/mk_util.py:2492](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L2492), [scripts/mk_util.py:2526](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L2526). The condition setting IS_CYGWIN_MINGW and usages of is_cygwin_mingw() supposes that is_cygwin_mingw() for the MinGW cross-compiling toolchain running on Cygwin, not for the Cygwin native compiling toolchain. Definitely native compiling on MSYS2 is more likely to compiling on Cygwin for itself, not cross-compiling.

I also looked around the whole appearance of '_CYGWIN' macro. As you said in #908 it changes the behavior of Z3, but many of them are unsignificant (like in [src/util/trace.h:23](https://github.com/Z3Prover/z3/blob/514f08f/src/util/trace.h#L23), and the rests are used with '_WINDOWS' which means the macro-defined sections should be used instead of other sections for OS X or Linux (because of the limits of Windows environment). Note that IS_CYGWIN always gets True before IS_CYGWIN_MINGW gets True ([scripts/mk_util.py:614](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L614) again), so the cross-compiled artifact of Z3 for Windows (cross-compiled in Cygwin) obviously has been defined '_CYGWIN' (because the condition making IS_CYGWIN True is same as the condition defining '_CYGWIN', see [scripts/mk_util.py:2469](https://github.com/Z3Prover/z3/blob/514f08f/scripts/mk_util.py#L2469)). In short, defining _CYGWIN in MSYS2 does not change the behavior of Z3 on Windows.

**Comment by wintersteiger** [comment]
This is now fixed (https://github.com/Z3Prover/z3/commit/e50470f2c4d561e42989d74b1a49e606c8e84415). 

Whether the _CYGWIN macro actually, in it's current version, changes the behavior of Z3 is ultimately irrelevant. If -D _CYGWIN is on, we will rely on the platform actually being cygwin and not mingw. Anyways, MSYS2 is now recognized as it's own platform.

**Comment by Uni-** [comment]
@wintersteiger Why did you decide shared object artifact to have `.so` extension? In MSYS2 it should be `.dll`.

**Comment by wintersteiger** [comment]
I assumed MSYS uses .so and binaries with .exe, if that's not so we should of course change that. The install path can be set manually and I'd really like to avoid have a huge list of default install paths for every option on flavors of unpopular OSs...

**Comment by wintersteiger** [comment]
Ah, I see, the .so/.dll gets put into bin instead of lib? Strange. May be related to the file extensions not matching up.

**Comment by wintersteiger** [comment]
(Should work as expected now.)

**Pull request closed without merging**
