### PR TITLE
Fix recent build system breakages

### PR DESCRIPTION
**Pull request by delcypher**
@NikolajBjorner 's recent changes for the python binding support in the build system broke the build for me. Here are a bunch of a fixes and also a small refactor

### CODE REVIEW

**Comment by wintersteiger** [comment]
Testing this atm.

**Comment by delcypher** [comment]
Great. Thanks :)

**Comment by wintersteiger** [comment]
On our OSX test machine the assertion at line 3584 failes because the Python `path` is not in `prefix`. See also #124. We should at the very least make sure that this works when users install the default packages from python.org. I think it's fine if homebrew, macports, and other managed installation throw errors or require another install directory setting.

**Comment by delcypher** [comment]
@wintersteiger Sorry about that. This was an oversight on my part 753f6d5 should hopefully fix that.

**Comment by delcypher** [comment]
@wintersteiger It might be worth noting as well that @NikolajBjorner changed the behaviour of the build system such that if the Python package directory is not under the install prefix the generated ``Makefile`` will not install the Python bindings. This is better than before because my PR (#338) would refuse to build if it detected this scenario. This might not be ideal.

If we do decide to make an exception for Python under OSX then we need to be very careful about how we do it because installing files outside the installation prefix is counter-intuitive and dangerous.

**Comment by wintersteiger** [comment]
So, the default intstallers from python.org install into `/Library/Frameworks/Python.framework/` (both 2.7 and 3.5) and the installer does not provide an option for installing into a different directory. I think the best way to handle this would be to add a conditional rule that installs into `/Library/...` when DESTDIR is not set. 

At the end of the installation we print "Z3py was installed at ..." and the configuration summary also prints the pkg dir. I think it would be fine to print a warning message if the python pkg dir is not under the prefix to make it clear to the user that they might break something if they go on.

**Comment by delcypher** [comment]
>  I think the best way to handle this would be to add a conditional rule that installs into /Library/... when DESTDIR is not set.

I was actually thinking of doing it slightly differently. I was thinking of providing an extra method(s) in ``MakeRuleCmd`` class that allows things to be installed outside the prefix and only allow it be used on OSX when the word ``python`` appears somewhere in the path. My reasoning here is that ``DESTDIR`` must always be respected. Doing this doesn't prevent a direct install on OSX because ``DESTDIR`` is not normally set so running ``make install`` would install into ``/Library/Frameworks/Python.framework/...``. If ``DESTDIR`` was set then it would end up installing to ``$(DESTDIR)/Library/Frameworks/Python.framework/...``.

Although branching on the value of ``DESTDIR`` inside the Makefile is possible I don't think that's a good route to go down.

**Comment by wintersteiger** [comment]
I see your reasoning, but at the time of running mk_make.py we don't really know whether DESTDIR will be used later or not, so that branch would have to be in the Makefile. If we detect an empty DESTDIR during mk_make.py then we would install into `/Library/...` even if DESTDIR is non-empty at the time of `make install`, right?

**Comment by delcypher** [comment]
@wintersteiger 
> I see your reasoning, but at the time of running mk_make.py we don't really know whether DESTDIR will be used later or not, so that branch would have to be in the Makefile. If we detect an empty DESTDIR during mk_make.py then we would install into /Library/... even if DESTDIR is non-empty at the time of make install, right?

No, I'm proposing something far more simple. Basically when generating the install command in the makefile rule for the Python bindings on OSX we will detect if the python package directory is in the prefix.

If it is then we emit the normal that we do normally.

```
	@cp z3*.py $(DESTDIR)$(PREFIX)/lib/python3.5/site-packages

```

if the python package directory is not in the prefix (and we are on OSX) then we emit this

```
        @echo WARNING python bindings are being installed outside of $(PREFIX)
	@cp z3*.py $(DESTDIR)/Library/Python/3.5/site-packages/ 
```

If we are not on OSX emission of the above is not allowed and running the python script will fail with an error.

If we do it this way

* We are still respecting ``DESTDIR`` in all cases
* If DESTDIR is empty (which it normally is) the bindings will still be installed on OSX to the right location for them to work.
* We emit a warning at install time about the dodgy install that we are doing. We could (and should) emit a warning at configure time too.
* On other platforms we can still ban installing outside of ``PREFIX``.

Does that make sense?

**Comment by wintersteiger** [comment]
Yeah, that sounds great, that way everybody should be happy. Are you ok making those changes to the current PR or should we do the merge first?

**Comment by delcypher** [comment]
I'll make the changes to this PR.

**Comment by delcypher** [comment]
@wintersteiger @NikolajBjorner 

I've added a patch that "should" mean that installing python bindings works under OSX.

Sorry this took longer than intended, I had to redo a lot of my changes when I rebase because they build system had already been changed.

**Pull request merged**
