### PR TITLE
Add translate method for FuncDecl in java api

### PR DESCRIPTION
**Pull request by chaserhkj**
When implementing a multithread application using z3, I find that I need to translate `FuncDecl` objects to another `Context`, but noticed that `FuncDecl` does not have a `translate(Context ctx)` method as `Expr` does. I think it indeed needs one so I implemented one for it.

### CODE REVIEW

**Comment by chaserhkj** [comment]
I forgot to get the docstrings done right, just fixed it.

**Comment by wintersteiger** [comment]
This should really not be necessary as `FuncDecl` inherits `translate` from `AST`. Is there some other problem that prevents the use of that?

**Comment by chaserhkj** [comment]
`FuncDecl` could not use `translate` from `AST`, cause `AST.translate()` is creating an `AST` java object, which cannot be cast to its heir class object `FuncDecl`. Doing so will yield a runtime exception.

In order to fix this, we need to implement either a `FuncDecl.translate()` like I did in this branch, or a dispatcher in `AST` to dispatch its object creation in `AST.translate()` to heir class constructors. (like `Expr.create()` in `Expr.translate()`, but maybe this could be done easier with java reflection)

**Comment by wintersteiger** [comment]
Oh yes, `AST.translate` needs to call `create`, that's a bug (which probably also exists in some of the other APIs).

**Pull request merged**
