### PR TITLE
MSAN Integration Build

### PR DESCRIPTION
**Pull request by evmaus**
This adds an MSAN build to azure-pipelines.yml per issue https://github.com/Z3Prover/z3/issues/2298

MSAN is a little weird, in that you need to link with a special copy of libc++ that's been compiled with MSAN in order to get good results (i.e. not just false positives).  The script this adds that runs at the start of the task downloads libc++ from SVN and builds it with MSAN, then uses that to link against Z3.  From testing with azure pipelines, the libc++ download and compilation seems to add a few minutes to the overall build, but certainly doesn't dominate.

Regression tests don't pass with MSAN at the moment--some of them trigger exit code 77 (which appears to be the exit code for "MSAN issue", according to a cursory search).

It seems like the example CMakes don't pick up the parameters passed for compiling/linking/etc, so I disabled those for MSAN's build.

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
I assume the Z3Build output is visible. 
Besides the odd return code of 77 it also has a set of warnings that are not flagged as errors and don't provide stack symbols.

(test fixed_bit_vector :time 0.00 :before-memory 4.59 :after-memory 4.59)
==14769==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x47f05e6  (/home/vsts/work/1/s/build/test-z3+0x47f05e6)
    #1 0x47f06c4  (/home/vsts/work/1/s/build/test-z3+0x47f06c4)
    #2 0x5ec4801  (/home/vsts/work/1/s/build/test-z3+0x5ec4801)
    #3 0x5ec38d0  (/home/vsts/work/1/s/build/test-z3+0x5ec38d0)
    #4 0x5c9b6c8  (/home/vsts/work/1/s/build/test-z3+0x5c9b6c8)
    #5 0x7f07e397782f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x42f278  (/home/vsts/work/1/s/build/test-z3+0x42f278)

  Uninitialized value was stored to memory at
    #0 0x47ecec2  (/home/vsts/work/1/s/build/test-z3+0x47ecec2)
    #1 0x5ec4732  (/home/vsts/work/1/s/build/test-z3+0x5ec4732)
    #2 0x5ec38d0  (/home/vsts/work/1/s/build/test-z3+0x5ec38d0)
    #3 0x5c9b6c8  (/home/vsts/work/1/s/build/test-z3+0x5c9b6c8)
    #4 0x7f07e397782f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

  Uninitialized value was stored to memory at
    #0 0x47ecec2  (/home/vsts/work/1/s/build/test-z3+0x47ecec2)
    #1 0x5ec4732  (/home/vsts/work/1/s/build/test-z3+0x5ec4732)
    #2 0x5ec38d0  (/home/vsts/work/1/s/build/test-z3+0x5ec38d0)
    #3 0x5c9b6c8  (/home/vsts/work/1/s/build/test-z3+0x5c9b6c8)
    #4 0x7f07e397782f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

**Comment by evmaus** [comment]
So I dug into this a little bit, and I think I've fixed the symbolization issue--we need to have llvm-symbolizer on the path (literally named that--Ubuntu puts llvm-symbolizer-x.x on the path), or have an environment variable set to the correct location for llvm-symbolizer (which I think I have right for Ubuntu 16.04).

I've committed something I think will fix the symbolization issue.  I'll wait for the build to complete and see if it did--if it didn't, I'll figure out the best way to set the variable across 'script' blocks.  (That seems to be the most likely issue.)

As far as the odd exit code, that's caused by MSAN issues in the regression tests.  I can either disable them for this build type (keeping a green build, but not showing the issues) or leave them as is.

**Comment by NikolajBjorner** [comment]
cool, now I can see it is related to the tbv test.

**Comment by evmaus** [comment]
Awesome; let me know if there's anything else that you'd like changed in this build.  :)

**Comment by NikolajBjorner** [comment]
the errors on the unit tests are now fixed. I disabled the regressions from the build as they fail for whatever other reason

**Pull request merged**
